# Порт веб-интерфейса который откроетсяя при подключении к точке доступа
WEB_PORT=5555

# --- Режим точки доступа ---
AP_ENABLED=1
AP_IFACE=wlan0
AP_ADDR=192.168.1.1
AP_PREFIX=24

AP_SSID=SMART-AGRO-mini
AP_PASSPHRASE=AgroSmart
AP_CHANNEL=6
AP_HW_MODE=g
AP_COUNTRY=EE

AP_WPA_MODE=2
AP_WPA_KEY_MGMT=WPA-PSK
AP_RSN_PAIRWISE=TKIP

DHCP_START=192.168.1.10
DHCP_END=192.168.1.100
DHCP_LEASE=12h

# --- Режим клиента ---
STA_ENABLED=0
STA_IFACE=wlan0
STA_SSID=
STA_PSK=
STA_HIDDEN=0


# --- Разрешить одновременную работу раздача + подключение к WiFi ---
ALLOW_CONCURRENT=1
# Стабильная работа не гарантируется! 
# Если 1 - попытается поднять AP+STA одновременно
# Если 0 - приоритет AP, либо явно отказ
